-- AddForeignKey
ALTER TABLE `TB_PESSOA` ADD CONSTRAINT `TB_PESSOA_ID_TB_PESSOA_RESPONSAVEL_FK` FOREIGN KEY (`TB_PESSOA_RESPONSAVEL_FK`) REFERENCES `TB_PESSOA`(`TB_PESSOA_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
