-- CreateTable
CREATE TABLE `TB_CARACTERISTICA_TIPO` (
    `TB_CARACTERISTICA_TIPO_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TB_CARACTERISTICA_TIPO_NOME` VARCHAR(16) NOT NULL,

    UNIQUE INDEX `TB_CARACTERISTICA_TIPO_NOME`(`TB_CARACTERISTICA_TIPO_NOME`),
    PRIMARY KEY (`TB_CARACTERISTICA_TIPO_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TB_CARACTERISTICA` (
    `TB_CARACTERISTICA_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TB_CARACTERISTICA_NOME` VARCHAR(16) NOT NULL,
    `TB_CARACTERISTICA_TIPO_ID_FK` INTEGER NOT NULL,

    UNIQUE INDEX `TB_CARACTERISTICA_NOME`(`TB_CARACTERISTICA_NOME`),
    PRIMARY KEY (`TB_CARACTERISTICA_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TB_CARAC_DESA` (
    `TB_CARAC_DESA_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TB_PESSOA_ID_FK` INTEGER NOT NULL,
    `TB_CARACTERISTICA_ID_FK` INTEGER NOT NULL,

    PRIMARY KEY (`TB_CARAC_DESA_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `TB_CARACTERISTICA` ADD CONSTRAINT `TB_CARACTERISTICA_ID_TB_CARACTERISTICA_TIPO_FK` FOREIGN KEY (`TB_CARACTERISTICA_TIPO_ID_FK`) REFERENCES `TB_CARACTERISTICA_TIPO`(`TB_CARACTERISTICA_TIPO_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `TB_CARAC_DESA` ADD CONSTRAINT `TB_CARAC_DESA_ID_TB_PESSOA_FK` FOREIGN KEY (`TB_PESSOA_ID_FK`) REFERENCES `TB_PESSOA`(`TB_PESSOA_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `TB_CARAC_DESA` ADD CONSTRAINT `TB_CARAC_DESA_ID_TB_CARACTERISTICA_FK` FOREIGN KEY (`TB_CARACTERISTICA_ID_FK`) REFERENCES `TB_CARACTERISTICA`(`TB_CARACTERISTICA_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
