-- CreateTable
CREATE TABLE `tb_anexo` (
    `TB_ANEXO_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CONTRIBUICAO_ID_FK` INTEGER NOT NULL,
    `TB_ANEXO_BINARIO` BLOB NOT NULL,
    `TB_ANEXO_NOME` VARCHAR(64) NOT NULL,

    INDEX `CONTRIBUICAO_ID_FK`(`CONTRIBUICAO_ID_FK`),
    PRIMARY KEY (`TB_ANEXO_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_apoia_caso` (
    `TB_APOIA_CASO_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CASO_ID_FK` INTEGER NOT NULL,
    `PESSOA_ID_FK` INTEGER NOT NULL,
    `TB_APOIA_CASO_DATA_ENTRADA` DATETIME(0) NOT NULL,
    `TB_APOIA_CASO_DATA_SAIDA` DATETIME(0) NULL,
    `TB_APOIA_CASO_ATIVIDADE` TIME(0) NULL,

    INDEX `CASO_ID_FK`(`CASO_ID_FK`),
    INDEX `PESSOA_ID_FK`(`PESSOA_ID_FK`),
    PRIMARY KEY (`TB_APOIA_CASO_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_carac_desa` (
    `TB_CARAC_DESA_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PESSOA_ID_FK` INTEGER NOT NULL,
    `CARACTERISTICA_ID_FK` INTEGER NOT NULL,

    INDEX `CARACTERISTICA_ID_FK`(`CARACTERISTICA_ID_FK`),
    INDEX `PESSOA_ID_FK`(`PESSOA_ID_FK`),
    PRIMARY KEY (`TB_CARAC_DESA_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_caracteristica` (
    `TB_CARACTERISTICA_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TB_CARACTERISTICA_NOME` VARCHAR(16) NOT NULL,
    `CARACTERISTICA_TIPO_ID_FK` INTEGER NOT NULL,

    INDEX `CARACTERISTICA_TIPO_ID_FK`(`CARACTERISTICA_TIPO_ID_FK`),
    PRIMARY KEY (`TB_CARACTERISTICA_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_caracteristica_tipo` (
    `TB_CARACTERISTICA_TIPO_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TB_CARACTERISTICA_TIPO_NOME` VARCHAR(16) NOT NULL,

    UNIQUE INDEX `TB_CARACTERISTICA_TIPO_NOME`(`TB_CARACTERISTICA_TIPO_NOME`),
    PRIMARY KEY (`TB_CARACTERISTICA_TIPO_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_caso` (
    `TB_CASO_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `STATUS_ID_FK` INTEGER NOT NULL,
    `PESSOA_ID_FK` INTEGER NOT NULL,
    `TB_CASO_TIPO_ID_FK` INTEGER NOT NULL,
    `ESTADO_ID_FK` INTEGER NOT NULL,
    `TB_CASO_CIDADE` VARCHAR(64) NOT NULL,
    `TB_CASO_BAIRRO` VARCHAR(64) NULL,
    `TB_CASO_RUA` VARCHAR(64) NULL,
    `TB_CASO_DESC` VARCHAR(512) NULL,
    `TB_CASO_DAT_INICIO` DATE NOT NULL,
    `TB_CASO_DAT_TERMINO` DATE NULL,

    INDEX `ESTADO_ID_FK`(`ESTADO_ID_FK`),
    INDEX `PESSOA_ID_FK`(`PESSOA_ID_FK`),
    INDEX `STATUS_ID_FK`(`STATUS_ID_FK`),
    INDEX `TB_CASO_TIPO_ID_FK`(`TB_CASO_TIPO_ID_FK`),
    PRIMARY KEY (`TB_CASO_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_caso_tipo` (
    `TB_CASO_TIPO_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TB_CASO_TIPO_NOME` VARCHAR(16) NOT NULL,

    UNIQUE INDEX `TB_CASO_TIPO_NOME`(`TB_CASO_TIPO_NOME`),
    PRIMARY KEY (`TB_CASO_TIPO_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_categoria` (
    `TB_CATEGORIA_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TB_CATEGORIA_NOME` VARCHAR(16) NOT NULL,

    UNIQUE INDEX `TB_CATEGORIA_NOME`(`TB_CATEGORIA_NOME`),
    PRIMARY KEY (`TB_CATEGORIA_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_certificado` (
    `TB_CERTIFICADO_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PESSOA_ID_FK` INTEGER NOT NULL,
    `TB_CERTIFICADO_DATA_HORA_EMISSAO` DATETIME(0) NULL,
    `TB_CERTIFICADO_BINARIO` BLOB NULL,
    `TB_CERTIFICADO_COD_EMISSAO` INTEGER NOT NULL,
    `TB_CERTIFICADO_CONCLUSAO` DATETIME(0) NOT NULL,

    UNIQUE INDEX `TB_CERTIFICADO_COD_EMISSAO`(`TB_CERTIFICADO_COD_EMISSAO`),
    INDEX `PESSOA_ID_FK`(`PESSOA_ID_FK`),
    PRIMARY KEY (`TB_CERTIFICADO_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_contribuicao` (
    `TB_CONTRIBUICAO_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `SESSAO_CHAT_ID_FK` INTEGER NOT NULL,
    `CATEGORIA_ID_FK` INTEGER NOT NULL,
    `TB_CONTRIBUICAO_DESC` VARCHAR(512) NOT NULL,
    `TB_CONTRIBUICAO_PONTOS` INTEGER UNSIGNED NULL,
    `TB_CONTRIBUICAO_DATA_HORA_ENVIO` DATETIME(0) NOT NULL,
    `TB_CONTRIBUICAO_EMISSOR` INTEGER NOT NULL,

    INDEX `CATEGORIA_ID_FK`(`CATEGORIA_ID_FK`),
    INDEX `SESSAO_CHAT_ID_FK`(`SESSAO_CHAT_ID_FK`),
    PRIMARY KEY (`TB_CONTRIBUICAO_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_estado` (
    `TB_ESTADO_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TB_ESTADO_NOME` CHAR(2) NOT NULL,

    UNIQUE INDEX `TB_ESTADO_NOME`(`TB_ESTADO_NOME`),
    PRIMARY KEY (`TB_ESTADO_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_mensagem` (
    `TB_MENSAGEM_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `SESSAO_CHAT_ID_FK` INTEGER NOT NULL,
    `TB_MENSAGEM_EMISSOR` INTEGER NOT NULL,
    `TB_MENSAGEM_RECEPTOR` INTEGER NOT NULL,
    `TB_MENSAGEM_DATA_HORA_ENVIO` DATETIME(0) NOT NULL,
    `TB_MENSAGEM_DESC` VARCHAR(1024) NOT NULL,

    INDEX `SESSAO_CHAT_ID_FK`(`SESSAO_CHAT_ID_FK`),
    PRIMARY KEY (`TB_MENSAGEM_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_pessoa` (
    `TB_PESSOA_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PESSOA_TIPO_ID_FK` INTEGER NOT NULL,
    `TB_PESSOA_NOME` VARCHAR(64) NOT NULL,
    `TB_PESSOA_SOBRENOME` VARCHAR(64) NULL,
    `TB_PESSOA_DATA_NASC` DATE NULL,
    `TB_PESSOA_CPF` INTEGER NULL,
    `TB_PESSOA_IDADE` INTEGER NULL,
    `TB_PESSOA_SEXO` VARCHAR(16) NULL,
    `TB_PESSOA_EMAIL` VARCHAR(128) NULL,
    `TB_PESSOA_SENHA` VARCHAR(64) NULL,
    `TB_PESSOA_TEL` VARCHAR(16) NULL,
    `TB_PESSOA_CEP` INTEGER NULL,
    `ESTADO_ID_FK` INTEGER NULL,
    `TB_PESSOA_CIDADE` VARCHAR(64) NULL,
    `TB_PESSOA_BIO` VARCHAR(256) NULL,
    `TB_PESSOA_PONTOS` INTEGER UNSIGNED NULL,
    `PESSOA_RESPONSAVEL_FK` INTEGER NULL,
    `TB_PESSOA_DEFIENCIA` VARCHAR(128) NULL,
    `TB_PESSOA_PARENTESCO` VARCHAR(16) NULL,
    `TB_PESSOA_IMAGEM` BLOB NULL,
    `TB_PESSOA_CARACTERISTICA_AD` VARCHAR(128) NULL,

    INDEX `ESTADO_ID_FK`(`ESTADO_ID_FK`),
    INDEX `PESSOA_RESPONSAVEL_FK`(`PESSOA_RESPONSAVEL_FK`),
    INDEX `PESSOA_TIPO_ID_FK`(`PESSOA_TIPO_ID_FK`),
    PRIMARY KEY (`TB_PESSOA_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_pessoa_tipo` (
    `TB_PESSOA_TIPO_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TB_PESSOA_TIPO_NOME` VARCHAR(16) NOT NULL,

    UNIQUE INDEX `TB_PESSOA_TIPO_NOME`(`TB_PESSOA_TIPO_NOME`),
    PRIMARY KEY (`TB_PESSOA_TIPO_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_sessao_chat` (
    `TB_SESSAO_CHAT_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `APOIA_CASO_ID_FK` INTEGER NOT NULL,

    INDEX `APOIA_CASO_ID_FK`(`APOIA_CASO_ID_FK`),
    PRIMARY KEY (`TB_SESSAO_CHAT_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `tb_status` (
    `TB_STATUS_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TB_STATUS_NOME` VARCHAR(16) NOT NULL,

    UNIQUE INDEX `TB_STATUS_NOME`(`TB_STATUS_NOME`),
    PRIMARY KEY (`TB_STATUS_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `tb_anexo` ADD CONSTRAINT `tb_anexo_ibfk_1` FOREIGN KEY (`CONTRIBUICAO_ID_FK`) REFERENCES `tb_contribuicao`(`TB_CONTRIBUICAO_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tb_apoia_caso` ADD CONSTRAINT `tb_apoia_caso_ibfk_1` FOREIGN KEY (`CASO_ID_FK`) REFERENCES `tb_caso`(`TB_CASO_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tb_apoia_caso` ADD CONSTRAINT `tb_apoia_caso_ibfk_2` FOREIGN KEY (`PESSOA_ID_FK`) REFERENCES `tb_pessoa`(`TB_PESSOA_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tb_carac_desa` ADD CONSTRAINT `tb_carac_desa_ibfk_1` FOREIGN KEY (`PESSOA_ID_FK`) REFERENCES `tb_pessoa`(`TB_PESSOA_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tb_carac_desa` ADD CONSTRAINT `tb_carac_desa_ibfk_2` FOREIGN KEY (`CARACTERISTICA_ID_FK`) REFERENCES `tb_caracteristica`(`TB_CARACTERISTICA_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tb_caracteristica` ADD CONSTRAINT `tb_caracteristica_ibfk_1` FOREIGN KEY (`CARACTERISTICA_TIPO_ID_FK`) REFERENCES `tb_caracteristica_tipo`(`TB_CARACTERISTICA_TIPO_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tb_caso` ADD CONSTRAINT `tb_caso_ibfk_1` FOREIGN KEY (`STATUS_ID_FK`) REFERENCES `tb_status`(`TB_STATUS_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tb_caso` ADD CONSTRAINT `tb_caso_ibfk_2` FOREIGN KEY (`PESSOA_ID_FK`) REFERENCES `tb_pessoa`(`TB_PESSOA_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tb_caso` ADD CONSTRAINT `tb_caso_ibfk_3` FOREIGN KEY (`ESTADO_ID_FK`) REFERENCES `tb_estado`(`TB_ESTADO_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tb_caso` ADD CONSTRAINT `tb_caso_ibfk_4` FOREIGN KEY (`TB_CASO_TIPO_ID_FK`) REFERENCES `tb_caso_tipo`(`TB_CASO_TIPO_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tb_certificado` ADD CONSTRAINT `tb_certificado_ibfk_1` FOREIGN KEY (`PESSOA_ID_FK`) REFERENCES `tb_pessoa`(`TB_PESSOA_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tb_contribuicao` ADD CONSTRAINT `tb_contribuicao_ibfk_1` FOREIGN KEY (`SESSAO_CHAT_ID_FK`) REFERENCES `tb_sessao_chat`(`TB_SESSAO_CHAT_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tb_contribuicao` ADD CONSTRAINT `tb_contribuicao_ibfk_2` FOREIGN KEY (`CATEGORIA_ID_FK`) REFERENCES `tb_categoria`(`TB_CATEGORIA_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tb_mensagem` ADD CONSTRAINT `tb_mensagem_ibfk_1` FOREIGN KEY (`SESSAO_CHAT_ID_FK`) REFERENCES `tb_sessao_chat`(`TB_SESSAO_CHAT_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tb_pessoa` ADD CONSTRAINT `tb_pessoa_ibfk_1` FOREIGN KEY (`PESSOA_TIPO_ID_FK`) REFERENCES `tb_pessoa_tipo`(`TB_PESSOA_TIPO_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tb_pessoa` ADD CONSTRAINT `tb_pessoa_ibfk_2` FOREIGN KEY (`ESTADO_ID_FK`) REFERENCES `tb_estado`(`TB_ESTADO_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tb_pessoa` ADD CONSTRAINT `tb_pessoa_ibfk_3` FOREIGN KEY (`PESSOA_RESPONSAVEL_FK`) REFERENCES `tb_pessoa`(`TB_PESSOA_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `tb_sessao_chat` ADD CONSTRAINT `tb_sessao_chat_ibfk_1` FOREIGN KEY (`APOIA_CASO_ID_FK`) REFERENCES `tb_apoia_caso`(`TB_APOIA_CASO_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
