/*
  Warnings:

  - You are about to drop the column `TB_CARACTERISTICA_AD` on the `tb_pessoa` table. All the data in the column will be lost.

*/
-- DropIndex
DROP INDEX `TB_CARACTERISTICA_NOME` ON `tb_caracteristica`;

-- AlterTable
ALTER TABLE `tb_pessoa` DROP COLUMN `TB_CARACTERISTICA_AD`,
    ADD COLUMN `TB_PESSOA_DESCRICAO` VARCHAR(191) NULL;

-- CreateTable
CREATE TABLE `TB_CASO` (
    `TB_CASO_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TB_CASO_TIPO_ID_FK` INTEGER NOT NULL,
    `TB_CASO_STATUS_ID_FK` INTEGER NOT NULL,
    `TB_CASO_PESSOA_ID_FK` INTEGER NOT NULL,
    `TB_CASO_ESTADO_ID_FK` INTEGER NOT NULL,
    `TB_CASO_CIDADE` VARCHAR(64) NOT NULL,
    `TB_CASO_BAIRRO` VARCHAR(64) NULL,
    `TB_CASO_RUA` VARCHAR(64) NULL,
    `TB_CASO_DESCRICAO` VARCHAR(512) NOT NULL,
    `TB_CASO_DATA_INICIO` DATETIME(3) NOT NULL,
    `TB_CASO_DAT_TERMINO` DATETIME(3) NULL,

    PRIMARY KEY (`TB_CASO_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TB_CASO_TIPO` (
    `TB_CASO_TIPO_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TB_CASO_TIPO_NOME` VARCHAR(16) NOT NULL,

    UNIQUE INDEX `TB_CASO_TIPO_NOME`(`TB_CASO_TIPO_NOME`),
    PRIMARY KEY (`TB_CASO_TIPO_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TB_CASO_STATUS` (
    `TB_CASO_STATUS_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TB_CASO_STATUS_NOME` VARCHAR(16) NOT NULL,

    UNIQUE INDEX `TB_CASO_STATUS_NOME`(`TB_CASO_STATUS_NOME`),
    PRIMARY KEY (`TB_CASO_STATUS_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TB_APOIA_CASO` (
    `TB_APOIA_CASO_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TB_PESSOA_ID_FK` INTEGER NOT NULL,
    `TB_CASO_ID_FK` INTEGER NOT NULL,
    `TB_APOIA_CASO_DATA_ENTRADA` DATETIME(3) NOT NULL,
    `TB_APOIA_CASO_DATA_SAIDA` DATETIME(3) NULL,
    `TB_APOIA_CASO_ATIVIDADE` DATETIME(3) NULL,

    PRIMARY KEY (`TB_APOIA_CASO_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `TB_CASO` ADD CONSTRAINT `TB_CASO_ID_TB_CASO_TIPO_FK` FOREIGN KEY (`TB_CASO_TIPO_ID_FK`) REFERENCES `TB_CASO_TIPO`(`TB_CASO_TIPO_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `TB_CASO` ADD CONSTRAINT `TB_CASO_ID_TB_CASO_STATUS_FK` FOREIGN KEY (`TB_CASO_STATUS_ID_FK`) REFERENCES `TB_CASO_STATUS`(`TB_CASO_STATUS_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `TB_CASO` ADD CONSTRAINT `TB_CASO_ID_TB_PESSOA_FK` FOREIGN KEY (`TB_CASO_PESSOA_ID_FK`) REFERENCES `TB_PESSOA`(`TB_PESSOA_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `TB_CASO` ADD CONSTRAINT `TB_CASO_ID_TB_ESTADO_FK` FOREIGN KEY (`TB_CASO_ESTADO_ID_FK`) REFERENCES `TB_ESTADO`(`TB_ESTADO_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `TB_APOIA_CASO` ADD CONSTRAINT `TB_APOIA_CASO_ID_TB_PESSOA_FK` FOREIGN KEY (`TB_PESSOA_ID_FK`) REFERENCES `TB_PESSOA`(`TB_PESSOA_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `TB_APOIA_CASO` ADD CONSTRAINT `TB_APOIA_CASO_ID_TB_CASO_FK` FOREIGN KEY (`TB_CASO_ID_FK`) REFERENCES `TB_CASO`(`TB_CASO_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
