-- AddForeignKey
ALTER TABLE `TB_CONTRIBUICAO` ADD CONSTRAINT `TB_CONTRIBUICAO_ID_TB_SESSAO_CHAT_FK` FOREIGN KEY (`TB_SESSAO_CHAT_ID_FK`) REFERENCES `TB_SESSAO_CHAT`(`TB_SESSAO_CHAT_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
