-- CreateTable
CREATE TABLE `TB_SESSAO_CHAT` (
    `TB_SESSAO_CHAT_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TB_APOIA_CASO_ID_FK` INTEGER NOT NULL,

    PRIMARY KEY (`TB_SESSAO_CHAT_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TB_CATEGORIA` (
    `TB_CATEGORIA_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TB_CATEGORIA_NOME` VARCHAR(16) NOT NULL,

    UNIQUE INDEX `TB_CATEGORIA_NOME`(`TB_CATEGORIA_NOME`),
    PRIMARY KEY (`TB_CATEGORIA_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TB_CONTRIBUICAO` (
    `TB_CONTRIBUICAO_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TB_SESSAO_CHAT_ID_FK` INTEGER NOT NULL,
    `TB_CATEGORIA_ID_FK` INTEGER NOT NULL,
    `TB_CONTRIBUICAO_DESCRICAO` VARCHAR(512) NOT NULL,
    `TB_CONTRIBUICAO_PONTOS` INTEGER UNSIGNED NULL,
    `TB_CONTRIBUICAO_DATA_HORA_ENVIO` DATETIME(3) NOT NULL,
    `TB_CONTRIBUICAO_EMISSOR` INTEGER NOT NULL,

    PRIMARY KEY (`TB_CONTRIBUICAO_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TB_ANEXO` (
    `TB_ANEXO_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TB_ANEXO_NOME` VARCHAR(64) NOT NULL,
    `TB_CONTRIBUICAO_ID_FK` INTEGER NOT NULL,

    PRIMARY KEY (`TB_ANEXO_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `TB_SESSAO_CHAT` ADD CONSTRAINT `TB_SESSAO_CHAT_ID_TB_APOIA_CASO_FK` FOREIGN KEY (`TB_APOIA_CASO_ID_FK`) REFERENCES `TB_APOIA_CASO`(`TB_APOIA_CASO_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `TB_CONTRIBUICAO` ADD CONSTRAINT `TB_CONTRIBUICAO_ID_TB_CATEGORIA_FK` FOREIGN KEY (`TB_CATEGORIA_ID_FK`) REFERENCES `TB_CATEGORIA`(`TB_CATEGORIA_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE `TB_ANEXO` ADD CONSTRAINT `TB_ANEXO_ID_TB_CONTRIBUICAO_FK` FOREIGN KEY (`TB_CONTRIBUICAO_ID_FK`) REFERENCES `TB_CONTRIBUICAO`(`TB_CONTRIBUICAO_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
